### ISSUE TITLE
Transactions run out of gas if #NUMBER_ADDRESS_PER_TXN = 1

### ISSUE THREAD

**Issue by kingjacob** [BisonTrails/lpt-miner#2]
<img width="698" alt="screen shot 2018-09-14 at 4 32 10 pm" src="https://user-images.githubusercontent.com/806312/45579346-d3281200-b83b-11e8-947e-bc208791364a.png">

**Potential fix:** replacing 170k with a higher number or adding some N constant since it works for higher #'s https://github.com/BisonTrails/lpt-miner/blob/2c4a410faa226579901bf3b3b2115a81bcaf2bf0/src/miner.js#L177

**Comment by aaronhenshaw** [comment]
I believe I pushed a fix to this -- https://github.com/BisonTrails/lpt-miner/commit/a8e14e848515565c83a2f1ef47f59584ec6ae1d6

let me know if it works.

**Comment by kingjacob** [comment]
That fix works. Thanks @aaronhenshaw
