### ISSUE TITLE
error creating txn SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by gjgd** [BisonTrails/lpt-miner#4]
Followed the steps, and when I run `npm start` I get this error

```
> lpt-miner@1.0.0 start /<path_to>/lpt-miner
> node --max-old-space-size=2048 txn-looper.js

Initializing txn looper [v2].
Grabbing address & http provider
Starting merkle mine batch with  1 addresses.
Using accounts in file: ./data/<my_account>
Retrieved accounts!
Creating Merkle tree...
Created Merkle tree with root <merkle_root> and 2598071 leaves
(0) Checking transaction <transaction>, <transaction>
Mining beginning...
txn completed... <transaction> for <transaction>
3290000000 'vs' '4000000000'
Using the Ethereum main network, Bulk Merkle Mine contract: 0xBfd0fb15e6C04b396EA12f5BB9Ba803E29B282Be
error creating txn <transaction> SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetchAccounts (/<path_to>/lpt-miner/src/miner.js:74:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

What should I do to fix it?

**Comment by mattnumber** [comment]
fyi - Just some data points in case they help with this issue--

I've been getting this, too - looks like the error's been coming up fairly constantly; my last completed txn was at ~ 8:12 a.m. Eastern this morning (September 24, 2018), and my max gas price + ETH balance are such that I'd've expected more txns to complete. Everything worked fine before then, and I didn't change anything that I know of that would've caused the problem. 

I have no pending txns. I stopped + restarted the script a few times, and I sent a little bit of ETH out of my mining address so I could update the LAST_TXNS field, and the error persists.

I feel like I've seen this happen before, and it has always gone away without me doing anything. 

**EDIT - Update @ 11:31:57 AM Eastern** - The script seems to be back on track now - it has progressed to the "Got <N> accounts to mine" step and beyond (though I can't report on whether txns are completing, bc I don't wanna raise my max gas price right now)

**Comment by aaronhenshaw** [comment]
@gjgd @mattnumber yeah this is because the livepeer address endpoint is down/inconsistent. They are working on it but I have built out a mysql fix that I will push to a different branch shortly. It will be a bit more technical than the previous one but I will try to provide some instructions asap.

Thank you both for reporting and for the info, I will try to get out the branch asap.

**Comment by gjgd** [comment]
Thanks @mattnumber  @aaronhenshaw. Script works for me as well now, you're right it's probably on Livepeer end. Closing the issue

**Comment by aaronhenshaw** [comment]
@gjgd @mattnumber updated a new branch 'mysql' so take a look if you want to get that running locally.

**Comment by mattnumber** [comment]
Thanks for the update! The whole mysql thing is a bit over my head, but I might try to figure it out tomorrow if I have time @aaronhenshaw
